apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/Khalil-EN/Healthcare_Microservices_Kubernetes.git
    targetRevision: main
    path: base/api-gateway
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true