apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway-service
  name: api-gateway-service
spec:
  type: ClusterIP
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      #nodePort: 30080  
  selector:
    app: apigateway
