apiVersion: v1
kind: Service
metadata:
  labels:
    app: patientservice
  name: patientservice
spec:
  ports:
    - name: "4002"
      port: 4002
      targetPort: 4002
  selector:
    app: patientservice
